### ISSUE TITLE
Archiving wheels

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/cargo-port#131]
I'd like to archive [h5py](https://pypi.python.org/pypi/h5py/2.7.1) for galaxyproject/galaxy#4519, but I don't think it'd be possible with the current `urls.tsv` format because linux builds have multiple versions for each CPython ABI (basically the default Unicode width, `cp27m` vs `cp27mu`).

I could also put them on wheels.galaxyproject.org, but cargo port seems like the better long term solution, especially since we did not generate the wheels.

Any ideas? I could add it to the version field, I guess? e.g. `2.7.1-cp27mu`?

**Comment by erasche** [comment]
Tagging the version works for me if that's OK with you.

**Comment by natefoo** [comment]
Works for me, thanks!
