### ISSUE TITLE
Bad hashes in log on jenkins

### ISSUE THREAD

**Issue by epruesse** [galaxyproject/cargo-port#158]
https://jenkins.galaxyproject.org/job/cargo-port/lastBuild/console

E.g.
```
INFO:root:Mimetype of samtools/samtools_1.9_src_all.tar.bz2 is samtools/samtools_1.9_src_all.tar.bz2:	bzip2 compressed data , block size = 900k
ERROR:root:File has bad hash! Refusing to serve this to end users.
```

**Comment by erasche** [comment]
Hi @epruesse,

Looks like something is wrong with the bioconda backup script. I'm not the author of that / not terribly familiar with its internals, but I can try and take a look at that tomorrow.

**Comment by erasche** [comment]
It seems to be because the urls.tsv file produced by the bioconda is the wrong format, it is missing the hashes, so all verification fails after that.

**Comment by erasche** [comment]
Hi @epruesse that seems to be a non-issue. The "bad hash" was from a 'dryrun' of the verifier. None of the hashes are present (I vaguely remember some discussion over this a long time ago with @bgruening) so the verifier complains. But there is nothing wrong with the packages. I've commented that out so the reports will be less confusing / full of "bad hash!"

**Comment by epruesse** [comment]
Thanks @erasche :)

I had just wanted to point it out. Logs like that have a tendency to remain ignored. Good to know everything is working as expected.
