### ISSUE TITLE
GSL.py needs some love

### ISSUE THREAD

**Issue by erasche** [galaxyproject/cargo-port#27]
Currently `gsl.py` downloads a copy of urls.tsv and then sorts through packages for the one desired.

It could be improved a fair bit:

- [ ] cache copy of urls.tsv, update that only if it has changed (nginx provides an ETag header for that file `:D`), we can use that to check if we need to fetch the whole file. (Think apt-get update)
- [ ] the install script needs to expose more flags 
  - [ ] package name 
  - [ ] version
  - [ ] architecture
  - [ ] attempt to fetch upstream or just use depot

**Comment by bgruening** [comment]
It would be nice to make gsl.py self-containing again and import all shared functions from gsl to other modules without breaking setuptools. I will look it this.

**Comment by erasche** [comment]
I wonder if we can't "compile" it like people do eith javascript. Write seperate things and have tools that merge them tkgether at the end?

**Comment by erasche** [comment]
Unlikely to be implemented given the present course of the project. Closing.
