### ISSUE TITLE
Upstream JS resource has bad SRI hash, datatables not loading on cargo-port

### ISSUE THREAD

**Issue by martenson** [galaxyproject/cargo-port#31]
getting js errors when accessing https://depot.galaxyproject.org/software/ and the cached URL list is empty

![screenshot 2015-12-17 14 58 14](https://cloud.githubusercontent.com/assets/1814954/11880435/a87a6ab8-a4ce-11e5-9e9e-01e00ba46efc.png)

**Comment by bgruening** [comment]
It worked 3h ago. We should ship these libraries locally and don't rely on upstream.

**Comment by erasche** [comment]
We're using SRI so we CAN rely on upstream.

Thanks @martenson, since this is the second time this has happened I'll start shipping these locally.

**Comment by erasche** [comment]
Chrome seems to really have issues with certain files/hashes, even though it passes all the tests. I don't understand `:|`

**Comment by erasche** [comment]
misleading title @martenson ;)

**Comment by erasche** [comment]
Fixed.

**Comment by martenson** [comment]
misleading but caught attention :P

**Comment by erasche** [comment]
Yes, yes it did. Seeing that title in my inbox was a surprise.

**Comment by martenson** [comment]
sorry man :)
