### ISSUE TITLE
SHA256SUM.txt hard coded to have file suffix of ".tar.gz"

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/cargo-port#51]
Examples:
- https://depot.galaxyproject.org/software/gemini-install/
- https://depot.galaxyproject.org/software/galaxy_json_data_source/

These are python `.py` files (`gemini-install_0.1_src_all.py`), but `SHA256SUM.txt ` contain e.g.:
```0e9a482c3f2b12a055fb73191b4d99c1e43a210471d16e539d85695b83ff3fc5  gemini-install_0.1_src_all.tar.gz```

**Comment by erasche** [comment]
hey, neat. This should be a very easy fix

**Comment by erasche** [comment]
https://github.com/galaxyproject/cargo-port/blob/master/upgrade.sh#L15

**Comment by erasche** [comment]
Fixed, pushed.

**Comment by blankenberg** [comment]
That was fast, thanks!
