### ISSUE TITLE
zlibbioc 1.14.0 checksum mismatch

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/cargo-port#63]
At the website (https://depot.galaxyproject.org/software/) cargo port says:
```
<action type="download_by_url" sha256sum="213cec750b14254df25e160463e28f3857ba703df1f3f43f7082dece8cfbf08b">
    https://depot.galaxyproject.org/software/zlibbioc/zlibbioc_1.14.0_src_all.tar.gz
</action>
```
This checksum should be `0811b4aecdb66a2ee33e806a40f54e0fdde2f4223a3981cccc16df9b7d3567d4`. It looks like the system confuses the following two files:
```
0811b4aecdb66a2ee33e806a40f54e0fdde2f4223a3981cccc16df9b7d3567d4  zlibbioc_1.14.0_src_all.tar.gz
213cec750b14254df25e160463e28f3857ba703df1f3f43f7082dece8cfbf08b  zlibbioc_1.14.0.tar.gz
```

**Comment by erasche** [comment]
ok, so `213cec` is correct according to upstream. It looks like the cargo port has a bad copy of `zlibbioc_1.14.0_src_all.tar.gz`. I'll get that removed + updated.

**Comment by erasche** [comment]
This should be resolved as of now.
