### ISSUE TITLE
FCGI Incorrect

### ISSUE THREAD

**Issue by erasche** [galaxyproject/cargo-port#68]
FCGI has a bad hash. It looks like upstream replaced the package, and we didn't have a good copy to start with. What should we do?

`Bad hash, 6125df9285fc22f1add8062ba06248a41b291659997948c670ead21aca943a73 != 08bf8afe1985b17d2375e8dc98ac86cab0daf017ccd5281157abdbb7e19273fd in FCGI/FCGI_0.67_src_all.tar.gz`

**Comment by erasche** [comment]
cc @martenson @bgruening @yhoogstrate 
(I get hourly emails until this is resolved so...pinging y'all explicity :) )

**Comment by bgruening** [comment]
Sorry traveling. What means we do not have a package this one was not yet included in cargo-port?

**Comment by erasche** [comment]
@bgruening no problem. No need to reply if you're busy.

- The package was added in the initial import with a specific sha256sum
- I [recently](https://github.com/galaxyproject/cargo-port/commit/ac4c322612f32f11b78e0e6b02a24023b8eebf7f) added a [tool](https://github.com/galaxyproject/cargo-port/commit/a4e99e0873791a82b870a090fb51b754a090f8bc) which verifies the sha256sums of every file on disk to ensure that they match what we expect, and remove them if they don't
- FCGI package was removed due to incorrect sha256sum (it should never have gotten to this state in the first place, but somehow it did)

I thought that upstreams hash != previous on-disk hash != urls.tsv hash, but apparently upstream's hash == previous on-disk, so I'll just update the urls.tsv.
