### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by erasche** [galaxyproject/cargo-port#72]
@bgruening shouldn't have to tell people "no later than one hour." This should happen automatically. Jenkins should tell users their package(s) are available.

cc @martenson

**Comment by bgruening** [comment]
:)

**Comment by erasche** [comment]
@martenson is this fixed now?

**Comment by martenson** [comment]
cargoport has a jenkins webhook now

**Comment by erasche** [comment]
Awesome! :D

**Comment by erasche** [comment]
Thanks @martenson
