### ISSUE TITLE
Training Data file

### ISSUE THREAD

**Issue by erasche** [galaxyproject/cargo-port#81]
- [ ] separate out training data
- [ ] choose subset of columns
- [ ] webpage support
- [ ] gsl/other script support?

**Comment by bgruening** [comment]
Keep it very simple:
 * filename
 * version (arbitrary but needs to be distinct)
 * URL

I don't think a hash is needed and this is also the biggest hurdle for people I think. Considering that this will be used by scientist, I would be in favour of skipping the checksum.

**Comment by erasche** [comment]
Data License? 

yeah, fine with dropping checksum.

**Comment by erasche** [comment]
Actually, how would you feel about auto-calculating checksum for them?

**Comment by bgruening** [comment]
What would be the use-case. Galaxy will not use it, right?
Data License, interesting ... but many will not have one I guess. So maybe optional.

**Comment by erasche** [comment]
Hmm, yeah, ok, not worth the effort. I feel like we should be doing a better job of tracking license restrictions across galaxy stuff, but .. oh well. No one licenses their data properly anyway.
