### ISSUE TITLE
Sort urls.tsv

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/cargo-port#88]
Sadly ``sort urls.tsv`` and even ``sort -n urls.tsv`` don't handle the version column nicely, but would be a simple way to define a consistent order for the file which would be easy to enforce on TravisCI, and apply when making manual additions.

**Comment by erasche** [comment]
Not to belittle what sounds like a sensible idea (more rules in travis), but what would be the return on investment for this feature be? I'd be a bit worried that it would be more of an annoyance to devs to have to conform to travis' opinions on ordering and manually re-ordering your file. I could see a rationale for automatically sorting+committing in jenkins/travis, but that's a bit of overhead to implement.

**Comment by peterjc** [comment]
I wanted to know where to insert new entries for #89, and since the file wasn't sorted by column one, this was unclear. I'd be happy with period manual re-sorting rather than enforcing a rule here?

**Comment by peterjc** [comment]
It looks like ``galaxy-cachefile-dedup`` aka ``bin/dedup.py`` does sorting?

**Comment by peterjc** [comment]
There's a bug in the dedup script (no new line after the header, also column names don't match README), fixed on #89.

**Comment by erasche** [comment]
> I'd be happy with period manual re-sorting rather than enforcing a rule here?

if you're happy with this, this may be the easiest way to go (unless one of us was just looking for a side project). In that case I might leave this ope
