### ISSUE TITLE
Rsync URL

### ISSUE THREAD

**Issue by erasche** [galaxyproject/cargo-port#95]
I know you'd like to do stuff with CVMFS and proper removal of SPOF, but if that isn't a short term solution, is there an rsync URL available? I'd like to ensure we at least have a complete clone of this _somewhere_ (with the knowledge that we'll do DNS round robin and etc. later)

**Comment by natefoo** [comment]
https://depot.galaxyproject.org/software is now accessible via rsync at rsync://depot.galaxyproject.org/software

**Comment by peterjc** [comment]
Having re-read #94, perhaps you mean this issue to cover creating a mirror with rsync (not just having the current site available to rsync from)?

**Comment by erasche** [comment]
It alao needs to be documented in the readme. I'll have a mirror available in 8 hours or so.

**Comment by erasche** [comment]
I downloaded a copy a long time ago, just never got around to making it publicly available

**Comment by erasche** [comment]
Fixed in https://github.com/galaxyproject/cargo-port/commit/fb8aa506e67b1de1afcbe2fea669341041768d42

Files are still copying across a network volume internally, but should be there by end of US business day.
